"""
Content routing skill.

Decides which content type and template should be used.
"""

from typing import Any, Dict

from .base import BaseSkill, SkillResult


class ContentRouterSkill(BaseSkill):
    name = "content_router"

    def run(self, payload: Dict[str, Any]) -> SkillResult:
        outline = payload.get("outline") or {}
        narration = payload.get("narration") or {}
        selected_segments = payload.get("selected_segments") or []
        if isinstance(selected_segments, dict):
            selected_segments = list(selected_segments.get("segments") or [])
        director_plan = payload.get("director_plan") or []

        target_duration = float(
            outline.get("target_duration_sec")
            or narration.get("target_duration_sec")
            or payload.get("duration_target")
            or 45
        )
        title_text = " ".join(
            str(value or "")
            for value in [
                outline.get("title"),
                outline.get("topic"),
                outline.get("summary"),
                narration.get("full_text"),
            ]
        ).lower()

        content_type = "deep_explainer"
        emotion_level = "medium"
        template_id = "deep_explainer_v1"

        conflict_keywords = [
            "争议", "翻车", "质疑", "冲突", "回应", "炮轰", "批评", "吵", "diss",
            "controvers", "critic", "clash", "backlash",
        ]
        news_keywords = [
            "发布", "宣布", "通报", "官宣", "记者会", "回应", "最新", "消息", "news",
            "announce", "launch", "report",
        ]

        has_conflict = any(keyword in title_text for keyword in conflict_keywords)
        has_news = any(keyword in title_text for keyword in news_keywords)
        many_segments = len(selected_segments) >= 4
        many_shots = len(director_plan) >= 6

        if has_conflict:
            content_type = "strong_conflict"
            emotion_level = "high"
            template_id = "strong_conflict_v1"
            if target_duration > 60:
                target_duration = 60
        elif has_news or target_duration <= 60:
            content_type = "fast_news"
            emotion_level = "medium"
            template_id = "fast_news_v1"
            target_duration = min(target_duration, 70)

        if many_segments and many_shots and target_duration >= 75:
            content_type = "deep_explainer"
            emotion_level = "low" if not has_conflict else emotion_level
            template_id = "deep_explainer_v1"

        return SkillResult(
            skill=self.name,
            version=self.version,
            output={
                "content_type": content_type,
                "emotion_level": emotion_level,
                "duration_target": int(round(target_duration)),
                "template_id": template_id,
            },
            meta={
                "status": "ready",
                "message": "Content route generated by rule-based classifier.",
            },
        )
