"""
Video quality check skill.
"""

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict

from .base import BaseSkill, SkillResult

PROJECT_ROOT = Path(__file__).resolve().parents[3]
REVIEW_SCRIPT = PROJECT_ROOT / "python" / "review" / "ai_video_review.py"


class QcCheckerSkill(BaseSkill):
    name = "qc_checker"

    def run(self, payload: Dict[str, Any]) -> SkillResult:
        video_path = str(payload.get("video_path") or "").strip()
        metadata_path = str(payload.get("metadata_path") or "").strip()
        output_path = str(payload.get("output_path") or "").strip()
        config_path = str(payload.get("config_path") or "").strip()

        if not video_path:
            return SkillResult(
                skill=self.name,
                version=self.version,
                output={"passed": False, "issues": []},
                meta={"status": "failed", "message": "video_path is required."},
            )

        if not metadata_path:
            return SkillResult(
                skill=self.name,
                version=self.version,
                output={"passed": False, "issues": []},
                meta={"status": "failed", "message": "metadata_path is required."},
            )

        if not output_path:
            output_path = str(Path(video_path).with_suffix(".qc_report.json"))

        cmd = [
            sys.executable,
            str(REVIEW_SCRIPT),
            "--video", video_path,
            "--metadata", metadata_path,
            "--output", output_path,
        ]
        if config_path:
            cmd.extend(["--config", config_path])

        try:
            result = subprocess.run(
                cmd,
                cwd=str(PROJECT_ROOT),
                capture_output=True,
                text=True,
                encoding="utf-8",
            )
        except Exception as exc:
            return SkillResult(
                skill=self.name,
                version=self.version,
                output={"passed": False, "issues": []},
                meta={"status": "failed", "message": f"Failed to start review script: {exc}"},
            )

        if result.returncode != 0:
            return SkillResult(
                skill=self.name,
                version=self.version,
                output={"passed": False, "issues": []},
                meta={
                    "status": "failed",
                    "message": "Review script returned non-zero exit code.",
                    "stderr": (result.stderr or "").strip()[-2000:],
                    "stdout": (result.stdout or "").strip()[-2000:],
                },
            )

        try:
            review_result = json.loads(Path(output_path).read_text(encoding="utf-8"))
        except Exception as exc:
            return SkillResult(
                skill=self.name,
                version=self.version,
                output={"passed": False, "issues": []},
                meta={"status": "failed", "message": f"Failed to read review output: {exc}"},
            )

        issues = []
        for item in review_result.get("fix_suggestions", []) or []:
            issues.append({
                "category": item.get("category"),
                "severity": item.get("severity"),
                "issue": item.get("issue"),
                "suggestion": item.get("suggestion"),
            })

        return SkillResult(
            skill=self.name,
            version=self.version,
            output={
                "passed": bool(review_result.get("passed")),
                "status": review_result.get("status"),
                "overall_score": review_result.get("overall_score"),
                "scores": review_result.get("scores", {}),
                "issues": issues,
                "review_result_path": output_path,
            },
            meta={
                "status": "ready",
                "message": "QC report generated by existing AI review workflow.",
            },
        )
